### ISSUE TITLE
Compute intersection for pairs within a MultiRoaringBitmap

### ISSUE THREAD

**Issue by daveuu** [andreasvc/roaringbitmap#16]
Feature request for a method like `MultiRoaringBitmap.jaccard_dist()` but for pairwise intersections. I realise a Python loop through `zip(indices1, indices2)` with calls to `MultiRoaringBitmap.intersection()` with pairs of indices will work, but a `MultiRoaringBitmap.intersection_pw()`-like function looping at the C-level would be quite a lot more :rocket:.

FWIW I have a slightly niche scenario of wanting to measure distances between many sets of sets. I plan to get the intersection of each set of sets, then measure the intersection of intersections between each pair. I'm thinking the denominator in a conventional jaccard distance wouldn't properly capture content of each set of sets . . . so I might use the union of each collection. Either way many fast intersections would be useful and the implementation might just be a cut down `MultiRoaringBitmap.jaccard_dist()`? (and potentially useful in other scenarios?)

**Comment by andreasvc** [comment]
Do you mean the cardinality of pairwise intersection/union? That would indeed be a simple variant of jaccard_dist(). Perhaps you could try it and make a pull request?

If you mean to get sets as a result, that might benefit less from a C-level implementation, because it involves the creation of lots of Python objects (the results). A more complex implementation could store the result compactly in a new MultiRoaringBitmap.

It seems a good idea to figure out which primitive operations are most useful to vectorize, so that other operations can be composed from them.

**Comment by daveuu** [comment]
Yes, I do mean cardinality of pairwise intersection/union - I'll give it a go when I get a chance.
