### ISSUE TITLE
access RoaringBitmap from cython for static typing

### ISSUE THREAD

**Issue by remiadon** [andreasvc/roaringbitmap#27]
I would like to `access the RoaringBitmap class from cython`, so I could use it for static typing inside my cython code.

The first problem I have is the package only contains  a `.pyx` file referring to the class
For now I have been trying to import other classes from your package (just for testing), assuming it would work if RoaringBitmap had a dedicated header file.

My current solution is the following
I have a `try_extern_cimport.pyx` file which contains
```python
cdef extern from "roaringbitmap/src/bitcount.h":
    unsigned int bit_clz(uint64_t) nogil
```
Installing the package via a `git clone` command inside the current dir and running `cythonize try_extern_cimport.pyx` actually works, but my point is doing it via a simple 'pip install'
###
I think `roaringbitmap.pyx` needs a dedicated header file and ideally this header file could be accessible via
```python
cdef extern from "roaringbitmap.h":
```

If I misunderstand something then sorry in advance, I am not even sure it is a practice to expose the header files of a cython package ...

**Comment by andreasvc** [comment]
You wouldn't use a .h file, but a .pxd file. See http://docs.cython.org/en/latest/src/userguide/sharing_declarations.html

A `RoaringBitmap` object is a Python object, implemented with a `cdef class`, and until now I only exposed it with a Python API. Therefore, any operation you do with it has to go through Python, and there is (as far as I understand) almost nothing to be gained from static typing and `cimport`ing `RoaringBitmap` from Cython headers in a `.pxd` file. In particular, as I recall, even `cdef` functions of a `cdef class` still go through the Python API, because they are part of a Python object, so for a Cython API to make sense, one would need to avoid using the `cdef class`.

What would need to happen for this to make sense is that it should be decided which functions will be exposed as a public Cython API, and these `cdef` functions and `struct`s should then be listed in a `.pxd` file. However, I'm not sure whether it is worth the effort. In general, it's always good to profile to identify bottlenecks before investing time in a potentially complicated change like this.

**Comment by remiadon** [comment]
Agreed, `.pyx` file, not `.h`, I got confused

Now, from what I understand, the way to do it would be to define a cdef `_RoaringBitmap` struct, which would be an attribute inside the RoaringBitmap `cdef class` (just like you do for `Block`), and then expose `cdef functions` taking pointers on these structs as arguments.

Anyway I understand this seems complicated and gives no guarantee over potential speedups.

Thank you
